remote_theme: pages-themes/minimal@v0.2.0
logo: /assets/img/profilephoto.png
plugins:
- jekyll-remote-theme
title: Brandon Quinones
description: Hi, my name is Brandon Quinones. I'm a Computer Science graduate based in Dallas, Texas, with a strong passion for programming. I currently work full-time as a Software Development Engineer in Test (SDET), and I'm eager to expand my skill set in data analysis and artificial intelligence to grow further in my career.